import * as React from "react";
import { Sidenote } from "./sidenote";
import { Callout, PullQuote, Marginalia } from "./callout";
import { Scene } from "./scene";
import {
  PollingFigure,
  ProactiveFigure,
  TripleFigure,
  WebhookTaxFigure,
  DigestPipelineFigure,
  DigestTimelineFigure,
  RuntimeFigure,
  PromptLayerFigure,
  GapMapFigure,
  TerminalsFigure,
  NamingFigure,
  SyncFallbackFigure,
  PostureFigure,
  MagicalInternFigure,
  InfraMapFigure,
  WishlistCategoriesFigure,
  PatternConvergeFigure,
  PulseClockFigure,
  PulseCompleteFigure,
  LandscapeGridFigure,
  LandscapeLayersFigure,
  PushFailureFigure,
  OrderingFigure,
  DemoVsProdFigure,
  MemoryDriftFigure,
  JudgmentGateFigure,
  ReviewReactiveFigure,
  ReviewSurfacesFigure,
  ReviewProactiveFigure,
  TokenStackFigure,
  CascadeFigure,
  LayerStackFigure,
  NamingEvolutionFigure,
  AdapterGrowthFigure,
  PareAsymmetryFigure,
  PatienceFigure,
  ExecutionGapFigure,
  CostCompareFigure,
  DeliveryChoiceFigure,
  FullPrimitiveFigure,
  CompoundGainsFigure,
  TwoLayerFigure,
  ContextDegradeFigure,
  ThreeActsEvolutionFigure,
  PrimitiveDiscoveryFigure,
  ProviderMultiplierFigure,
  ComplexityGradientFigure,
  CRContextFigure,
  CRScheduleGapFigure,
  PHEnricherFigure,
  PHSignalGapFigure,
} from "./figures";

export const mdxComponents = {
  Sidenote,
  Callout,
  PullQuote,
  Marginalia,
  Scene,
  PollingFigure,
  ProactiveFigure,
  TripleFigure,
  WebhookTaxFigure,
  DigestPipelineFigure,
  DigestTimelineFigure,
  RuntimeFigure,
  PromptLayerFigure,
  GapMapFigure,
  TerminalsFigure,
  NamingFigure,
  SyncFallbackFigure,
  PostureFigure,
  MagicalInternFigure,
  InfraMapFigure,
  WishlistCategoriesFigure,
  PatternConvergeFigure,
  PulseClockFigure,
  PulseCompleteFigure,
  LandscapeGridFigure,
  LandscapeLayersFigure,
  PushFailureFigure,
  OrderingFigure,
  DemoVsProdFigure,
  MemoryDriftFigure,
  JudgmentGateFigure,
  ReviewReactiveFigure,
  ReviewSurfacesFigure,
  ReviewProactiveFigure,
  TokenStackFigure,
  CascadeFigure,
  LayerStackFigure,
  NamingEvolutionFigure,
  AdapterGrowthFigure,
  PareAsymmetryFigure,
  PatienceFigure,
  ExecutionGapFigure,
  CostCompareFigure,
  DeliveryChoiceFigure,
  FullPrimitiveFigure,
  CompoundGainsFigure,
  TwoLayerFigure,
  ContextDegradeFigure,
  ThreeActsEvolutionFigure,
  PrimitiveDiscoveryFigure,
  ProviderMultiplierFigure,
  ComplexityGradientFigure,
  CRContextFigure,
  CRScheduleGapFigure,
  PHEnricherFigure,
  PHSignalGapFigure,
  LinkedInEmbed: () => (
    <iframe
      src="https://www.linkedin.com/embed/feed/update/urn:li:share:7429634994467414016?collapsed=1"
      height="264"
      width="504"
      frameBorder="0"
      allowFullScreen
      title="Embedded post"
      className="mx-auto max-w-full rounded-xl"
    />
  ),
  iframe: (props: React.IframeHTMLAttributes<HTMLIFrameElement>) => (
    <iframe className="mx-auto my-8 max-w-full rounded-xl" {...props} />
  ),
  // Wobbly highlight on inline strong
  mark: (props: React.HTMLAttributes<HTMLElement>) => (
    <mark className="scribble-highlight bg-transparent text-ink" {...props} />
  ),
};
